"""server_default to default

Revision ID: 93004c359f50
Revises: b5f78fe0b769
Create Date: 2024-03-05 20:55:35.974704

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93004c359f50'
down_revision: Union[str, None] = 'b5f78fe0b769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'date_created',
                    server_default=False, default=datetime.utcnow)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'date_created',
                    server_default=sa.func.now(), default=False)
    pass
    # ### end Alembic commands ###
