"""add users table

Revision ID: 00a126fcbdfc
Revises: a8cdbf1f9fbe
Create Date: 2024-03-28 18:49:26.048036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a126fcbdfc'
down_revision: Union[str, None] = 'a8cdbf1f9fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("create schema users"))
    op.create_table('users',
                    sa.Column('id', sa.CHAR(length=36), nullable=False),
                    sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('users_pk')),
                    schema='users'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='users')
    op.execute(sa.text("drop schema users"))
    # ### end Alembic commands ###
