
name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Run command on remote server
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{secrets.SSH_HOST}}
        user: ${{secrets.SSH_USER}}
        private_key: ${{secrets.SSH_PRIVATE_KEY}}
        command: |
          echo '--- START WORK ON REMOTE SERVER ---';
          cd ${{ secrets.PROJECT_FOLDER }};
          echo '--- LIST OF FILES ---';
          ls -al;
          echo '--- GIT INFORMATION ---'
          git co master;
          git pull;
          echo '--- LIST OF DOCKER CONTAINERS AFTER STOPING DOCKER CONTAINERS ---';
          docker compose up -d --build;
          echo '--- LIST OF DOCKER CONTAINERS AFTER STARTING DOCKER CONTAINERS ---';
          docker ps;